"""Base protocol and abstractions for all arbitrage strategies."""
from __future__ import annotations

from abc import ABC, abstractmethod
from decimal import Decimal
from typing import Any, Optional, Protocol, runtime_checkable

from pydantic import BaseModel, Field

from src.core.models import OrderSide, OrderType, Signal, Trade


class TradeLeg(BaseModel):
    """A single leg of a multi-leg trade."""

    exchange_id: str
    symbol: str
    side: OrderSide
    size: Decimal
    order_type: OrderType = OrderType.MARKET
    price: Optional[Decimal] = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class TradeRequest(BaseModel):
    """Request generated by a strategy; executed by the execution engine."""

    strategy_id: str
    legs: list[TradeLeg]
    expected_profit_usdt: Decimal = Decimal("0")
    confidence: float = 1.0
    metadata: dict[str, Any] = Field(default_factory=dict)


class StrategyMetrics(BaseModel):
    """Runtime metrics for a strategy."""

    signals_received: int = 0
    trade_requests_generated: int = 0
    fills_received: int = 0
    total_realized_pnl_usdt: Decimal = Decimal("0")
    signals_filtered: int = 0  # below threshold or risk rejected


@runtime_checkable
class CostCalculator(Protocol):
    """Protocol for estimating friction costs (fees + slippage) per leg."""

    def estimate_cost(
        self,
        exchange_id: str,
        symbol: str,
        side: OrderSide,
        size: Decimal,
        price: Decimal,
    ) -> Decimal:
        """Return estimated cost in USDT for one trade leg."""
        ...


class BaseStrategy(ABC):
    """Abstract base for all arbitrage strategies."""

    def __init__(
        self,
        strategy_id: str,
        cost_calculator: CostCalculator,
        shadow_mode: bool = False,
    ) -> None:
        self._strategy_id = strategy_id
        self._cost_calculator = cost_calculator
        self._is_active = False
        self._shadow_mode = shadow_mode
        self._metrics = StrategyMetrics()

    @property
    def strategy_id(self) -> str:
        return self._strategy_id

    @property
    def is_active(self) -> bool:
        return self._is_active

    @property
    def shadow_mode(self) -> bool:
        return self._shadow_mode

    @shadow_mode.setter
    def shadow_mode(self, value: bool) -> None:
        self._shadow_mode = value

    @property
    def metrics(self) -> StrategyMetrics:
        return self._metrics

    async def start(self) -> None:
        self._is_active = True

    async def stop(self) -> None:
        self._is_active = False

    @abstractmethod
    async def on_signal(self, signal: Signal) -> Optional[TradeRequest]:
        """Process incoming signal; return TradeRequest or None."""
        ...

    async def on_fill(self, trade: Trade) -> None:
        """Handle fill notification and update metrics."""
        self._metrics.fills_received += 1
